server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://yangs-itus.mysql.rds.aliyuncs.com:3306/rwc?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Wl110511
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    show-sql: true
  redis:
    host: 49.233.182.231
    port: 6379
    timeout: 5000
    password: wl110511
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
  freemarker:
    cache: false
    suffix: .ftl
    template-loader-path: classpath:/templates/
mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath:mappers/*.xml
logging:
  level:
    root: debug